version: '3'
services:
  crypto-tracker:
    container_name: crypto-tracker
    image: crypto-tracker
    build:
      context: .
    volumes:
      - ./:/opt/www
    ports:
      - 9501:9501
    environment:
      - APP_ENV=dev
      - SCAN_CACHEABLE=false
      - DB_DRIVER=mysql
      - DB_HOST=mysql
      - DB_PORT=3306
      - DB_DATABASE=crypto_tracker
      - DB_USERNAME=root
      - DB_PASSWORD=root
      - DB_CHARSET=utf8mb4
      - DB_COLLATION=utf8mb4_unicode_ci

  mysql:
    image: mysql:5.7
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=crypto_tracker
    ports:
      - 3306:3306

networks:
  default:
    name: crypto-tracker
